name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'website/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./website
      run: npm ci
      
    - name: Build project
      working-directory: ./website
      run: npm run build
      env:
        VITE_BSC_RPC: ${{ secrets.VITE_BSC_RPC }}
        VITE_BSC_TESTNET_RPC: ${{ secrets.VITE_BSC_TESTNET_RPC }}
        VITE_ETHEREUM_RPC: ${{ secrets.VITE_ETHEREUM_RPC }}
        VITE_USDOX_CONTRACT: ${{ secrets.VITE_USDOX_CONTRACT }}
        VITE_RUSDOX_CONTRACT: ${{ secrets.VITE_RUSDOX_CONTRACT }}
        VITE_STAKING_REWARD_CONTRACT: ${{ secrets.VITE_STAKING_REWARD_CONTRACT }}
        VITE_MASTER_CHEF_CONTRACT: ${{ secrets.VITE_MASTER_CHEF_CONTRACT }}
        VITE_OWNER1_ADDRESS: ${{ secrets.VITE_OWNER1_ADDRESS }}
        VITE_OWNER2_ADDRESS: ${{ secrets.VITE_OWNER2_ADDRESS }}
        VITE_ALCHEMY_RPC: ${{ secrets.VITE_ALCHEMY_RPC }}
        VITE_INFURA_RPC: ${{ secrets.VITE_INFURA_RPC }}
        VITE_ETHERSCAN_API_KEY: ${{ secrets.VITE_ETHERSCAN_API_KEY }}
        VITE_COINMARKETCAP_API_KEY: ${{ secrets.VITE_COINMARKETCAP_API_KEY }}
        VITE_APP_NAME: "TheUSDOX"
        VITE_APP_VERSION: "1.0.0"
        VITE_APP_DESCRIPTION: "The On-Chain Dollar Revolution"
        VITE_DOMAIN: "theusdox.com"
        VITE_DEVELOPER_EMAIL: "hello@theusdox.com"
        VITE_TWITTER_URL: "https://x.com/TheUSDOXs"
        VITE_TELEGRAM_URL: "https://t.me/theusdox"
        VITE_DISCORD_URL: "https://discord.gg/K49Nu2Jbz"
        VITE_GITHUB_URL: "https://github.com/theusdox"
        VITE_ENVIRONMENT: "production"
        VITE_DEBUG: "false"
        VITE_NETWORK: "bsc-mainnet"
        
    - name: Deploy to Vercel (Preview)
      if: github.event_name == 'pull_request'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./website
        scope: ${{ secrets.VERCEL_ORG_ID }}
        
    - name: Deploy to Vercel (Production)
      if: github.ref == 'refs/heads/main'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: ./website
        scope: ${{ secrets.VERCEL_ORG_ID }}
        
    - name: Comment deployment URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const { data: deployments } = await github.rest.repos.listDeployments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.payload.pull_request.head.sha,
            per_page: 1
          });
          
          if (deployments.length > 0) {
            const deploymentUrl = `https://theusdox-dapp-git-${context.payload.pull_request.head.ref}-vkathushan.vercel.app`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Deployment successful!**\n\n📱 **Preview URL**: ${deploymentUrl}\n\n✅ Your changes are now live for preview.`
            });
          }